import sublime
from _typeshed import Incomplete

class ProgressReporter:
    title: Incomplete
    _message: str | None
    _percentage: int | float | None
    def __init__(self, title: str) -> None: ...
    def __del__(self) -> None: ...
    def _render(self) -> str: ...
    def __call__(self, message: str | None, percentage: float | None) -> None: ...

class ViewProgressReporter(ProgressReporter):
    _view: Incomplete
    _key: Incomplete
    def __init__(self, view: sublime.View, key: str, title: str, message: str | None = None, percentage: float | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: float | None = None) -> None: ...

class WindowProgressReporter(ProgressReporter):
    _window: Incomplete
    _key: Incomplete
    def __init__(self, window: sublime.Window, key: str, title: str, message: str | None = None, percentage: float | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: float | None = None) -> None: ...

class ApplicationProgressReporter(ProgressReporter):
    _key: Incomplete
    def __init__(self, key: str, title: str, message: str | None = None, percentage: float | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: float | None = None) -> None: ...
