import sublime
from .logging import debug as debug
from .protocol import SignatureHelp as SignatureHelp, SignatureInformation as SignatureInformation
from .registry import LspTextCommand as LspTextCommand
from .views import FORMAT_MARKUP_CONTENT as FORMAT_MARKUP_CONTENT, FORMAT_STRING as FORMAT_STRING, MarkdownLangMap as MarkdownLangMap, minihtml as minihtml

class LspSignatureHelpNavigateCommand(LspTextCommand):
    def want_event(self) -> bool: ...
    def run(self, _: sublime.Edit, forward: bool) -> None: ...

class LspSignatureHelpShowCommand(LspTextCommand):
    def want_event(self) -> bool: ...
    def run(self, _: sublime.Edit) -> None: ...

class SigHelp:
    def __init__(self, state: SignatureHelp, language_map: MarkdownLangMap | None) -> None: ...
    @classmethod
    def from_lsp(cls, sighelp: SignatureHelp | None, language_map: MarkdownLangMap | None) -> SigHelp | None: ...
    def render(self, view: sublime.View) -> str: ...
    def active_signature_help(self) -> SignatureHelp: ...
    def has_multiple_signatures(self) -> bool: ...
    def select_signature(self, forward: bool) -> None: ...
