import abc
import socket
import subprocess
import threading
import weakref
from .constants import ST_PLATFORM as ST_PLATFORM
from .logging import debug as debug, exception_log as exception_log
from .promise import PackagedTask as PackagedTask, Promise as Promise
from .protocol import JSONRPCMessage as JSONRPCMessage
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from io import BufferedIOBase
from queue import Queue
from typing import Any, Callable, IO
from typing_extensions import override

TCP_CONNECT_TIMEOUT: int

class StopLoopError(Exception): ...

class TransportConfig(ABC, metaclass=abc.ABCMeta):
    @staticmethod
    def resolve_launch_config(command: list[str], env: dict[str, str] | None, variables: dict[str, str]) -> LaunchConfig: ...
    @abstractmethod
    def start(self, command: list[str] | None, env: dict[str, str] | None, cwd: str | None, variables: dict[str, str], callbacks: TransportCallbacks) -> TransportWrapper: ...

class StdioTransportConfig(TransportConfig):
    @override
    def start(self, command: list[str] | None, env: dict[str, str] | None, cwd: str | None, variables: dict[str, str], callbacks: TransportCallbacks) -> TransportWrapper: ...

class TcpClientTransportConfig(TransportConfig):
    _port: Incomplete
    def __init__(self, port: int | None) -> None: ...
    @override
    def start(self, command: list[str] | None, env: dict[str, str] | None, cwd: str | None, variables: dict[str, str], callbacks: TransportCallbacks) -> TransportWrapper: ...
    def _connect(self, port: int) -> socket.socket: ...

class TcpServerTransportConfig(TransportConfig):
    _port: Incomplete
    def __init__(self, port: int | None) -> None: ...
    @override
    def start(self, command: list[str] | None, env: dict[str, str] | None, cwd: str | None, variables: dict[str, str], callbacks: TransportCallbacks) -> TransportWrapper: ...

class TransportCallbacks:
    def on_transport_close(self, exit_code: int, exception: Exception | None) -> None: ...
    def on_payload(self, payload: JSONRPCMessage) -> None: ...
    def on_stderr_message(self, message: str) -> None: ...

class Transport(ABC, metaclass=abc.ABCMeta):
    _encoder: Incomplete
    _decoder: Incomplete
    def __init__(self, encoder: Callable[[JSONRPCMessage], bytes], decoder: Callable[[bytes], JSONRPCMessage]) -> None: ...
    @abstractmethod
    def read(self) -> JSONRPCMessage | None: ...
    @abstractmethod
    def write(self, payload: JSONRPCMessage) -> None: ...
    @abstractmethod
    def write_bytes(self, payload: bytes) -> None: ...
    @abstractmethod
    def close(self) -> None: ...

class FileObjectTransport(Transport):
    _reader: Incomplete
    _writer: Incomplete
    def __init__(self, encoder: Callable[[JSONRPCMessage], bytes], decoder: Callable[[bytes], JSONRPCMessage], reader: IO[bytes] | BufferedIOBase, writer: IO[bytes] | BufferedIOBase) -> None: ...
    @override
    def read(self) -> JSONRPCMessage: ...
    @override
    def write(self, payload: JSONRPCMessage) -> None: ...
    @override
    def write_bytes(self, payload: bytes) -> None: ...
    @override
    def close(self) -> None: ...

class SocketTransport(FileObjectTransport):
    _socket: Incomplete
    def __init__(self, encoder: Callable[[JSONRPCMessage], bytes], decoder: Callable[[bytes], JSONRPCMessage], sock: socket.socket) -> None: ...
    @override
    def close(self) -> None: ...

class TransportWrapper:
    _closed: bool
    _callback_object: Incomplete
    _transport: Incomplete
    _process: Incomplete
    _error_reader: Incomplete
    _reader_thread: Incomplete
    _writer_thread: Incomplete
    _send_queue: Queue[JSONRPCMessage | bytes | None]
    def __init__(self, callback_object: TransportCallbacks, transport: Transport, process: subprocess.Popen[bytes] | None, error_reader: ErrorReader | None) -> None: ...
    @property
    def process_args(self) -> Any: ...
    def send(self, payload: JSONRPCMessage) -> None: ...
    def send_bytes(self, payload: bytes) -> None: ...
    def close(self) -> None: ...
    def _read_loop(self) -> None: ...
    def _end(self, exception: Exception | None) -> None: ...
    def _write_loop(self) -> None: ...

class LaunchConfig:
    __slots__: Incomplete
    command: list[str]
    env: dict[str, str]
    def __init__(self, command: list[str], env: dict[str, str] | None = None) -> None: ...
    def start(self, cwd: str | None, stdin: int, stdout: int, stderr: int) -> subprocess.Popen[bytes]: ...

class ErrorReader:
    _callback_object: Incomplete
    _reader: Incomplete
    _thread: Incomplete
    def __init__(self, callback_object: TransportCallbacks, reader: IO[bytes]) -> None: ...
    def on_transport_close(self) -> None: ...
    def _loop(self) -> None: ...

def encode_json(data: JSONRPCMessage) -> bytes: ...
def decode_json(message: bytes) -> JSONRPCMessage: ...

g_subprocesses: weakref.WeakSet[subprocess.Popen[bytes]]

def kill_all_subprocesses() -> None: ...
def _fixup_startup_args(args: list[str]) -> Any: ...
def _start_subprocess(args: list[str], stdin: int, stdout: int, stderr: int, startupinfo: Any, env: dict[str, str], cwd: str | None) -> subprocess.Popen[bytes]: ...
def _find_free_port() -> int: ...
def _add_and_resolve_port_variable(variables: dict[str, str], port: int | None) -> int: ...
def _join_thread(t: threading.Thread) -> None: ...
