import abc
import contextlib
import sublime
from ...protocol import DocumentSelector as DocumentSelector, DocumentUri as DocumentUri, FileOperationFilter as FileOperationFilter, ServerCapabilities as ServerCapabilities, TextDocumentSyncKind, TextDocumentSyncOptions as TextDocumentSyncOptions, URI as URI
from .collections import DottedDict as DottedDict
from .constants import LANGUAGE_IDENTIFIERS as LANGUAGE_IDENTIFIERS, MarkdownLangMap as MarkdownLangMap
from .file_watcher import FileWatcherEventType as FileWatcherEventType
from .logging import debug as debug, set_debug_logging as set_debug_logging
from .transports import StdioTransportConfig as StdioTransportConfig, TcpClientTransportConfig as TcpClientTransportConfig, TcpServerTransportConfig as TcpServerTransportConfig, TransportConfig as TransportConfig
from .url import filename_to_uri as filename_to_uri, parse_uri as parse_uri
from .workspace import WorkspaceFolder as WorkspaceFolder
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Generator, Iterable, TypeVar, TypedDict
from typing_extensions import NotRequired, override

FEATURES_TIMEOUT: int
PANEL_FILE_REGEX: str
PANEL_LINE_REGEX: str
MarkdownLangMapJson = dict[str, list[list[str]]]

class FileWatcherConfig(TypedDict):
    patterns: list[str]
    events: NotRequired[list[FileWatcherEventType]]
    ignores: NotRequired[list[str]]

class ViewStatusHandler(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def on_view_status_changed(self, config_name: str, view: sublime.View, status: str | None) -> None: ...

def basescope2languageid(base_scope: str) -> str: ...
@contextlib.contextmanager
def runtime(token: str) -> Generator[None, None, None]: ...
T = TypeVar('T')

def diff(old: Iterable[T], new: Iterable[T]) -> tuple[set[T], set[T]]: ...
def matches_pattern(path: str, patterns: Any) -> bool: ...
def sublime_pattern_to_glob(pattern: str, *, is_directory_pattern: bool, root_path: str | None = None) -> str: ...
def debounced(f: Callable[[], Any], timeout_ms: int = 0, condition: Callable[[], bool] = ..., async_thread: bool = False) -> None: ...

class SettingsRegistration:
    __slots__: Incomplete
    settings: Incomplete
    settings_path: Incomplete
    def __init__(self, settings: sublime.Settings, settings_path: str, on_change: Callable[[SettingsRegistration], None]) -> None: ...
    def __del__(self) -> None: ...

class DebouncerNonThreadSafe:
    _async_thread: Incomplete
    _current_id: int
    _next_id: int
    def __init__(self, async_thread: bool) -> None: ...
    def debounce(self, f: Callable[[], None], timeout_ms: int = 0, condition: Callable[[], bool] = ...) -> None: ...
    def cancel_pending(self) -> None: ...

def read_dict_setting(settings_obj: sublime.Settings, key: str, default: dict) -> dict: ...
def read_list_setting(settings_obj: sublime.Settings, key: str, default: list) -> list: ...

class Settings:
    completion_insert_mode: Incomplete
    diagnostics_additional_delay_auto_complete_ms: Incomplete
    diagnostics_delay_ms: Incomplete
    diagnostics_gutter_marker: Incomplete
    diagnostics_highlight_style: Incomplete
    diagnostics_panel_include_severity_level: Incomplete
    disabled_capabilities: Incomplete
    document_highlight_style: Incomplete
    format_on_type: Incomplete
    hover_highlight_style: Incomplete
    inhibit_snippet_completions: Incomplete
    inhibit_word_completions: Incomplete
    initially_folded: Incomplete
    inlay_hints_max_length: Incomplete
    link_highlight_style: Incomplete
    log_debug: Incomplete
    log_max_size: Incomplete
    log_server: Incomplete
    lsp_code_actions_on_format: Incomplete
    lsp_code_actions_on_save: Incomplete
    lsp_format_on_paste: Incomplete
    lsp_format_on_save: Incomplete
    on_save_task_timeout_ms: Incomplete
    only_show_lsp_completions: Incomplete
    popup_max_characters_height: Incomplete
    popup_max_characters_width: Incomplete
    refactoring_auto_save: Incomplete
    semantic_highlighting: Incomplete
    show_code_actions: Incomplete
    show_code_actions_in_hover: Incomplete
    show_code_lens: Incomplete
    show_diagnostics_annotations_severity_level: Incomplete
    show_diagnostics_count_in_view_status: Incomplete
    show_diagnostics_in_hover: Incomplete
    show_diagnostics_in_view_status: Incomplete
    show_diagnostics_panel_on_save: Incomplete
    show_diagnostics_severity_level: Incomplete
    show_inlay_hints: Incomplete
    show_multiline_diagnostics_highlights: Incomplete
    show_multiline_document_highlights: Incomplete
    show_references_in_quick_panel: Incomplete
    show_signature_help: Incomplete
    show_symbol_action_links: Incomplete
    show_view_status: Incomplete
    def __init__(self, s: sublime.Settings) -> None: ...
    def update(self, s: sublime.Settings) -> None: ...
    def highlight_style_region_flags(self, style_str: str) -> tuple[sublime.RegionFlags, sublime.RegionFlags]: ...
    @staticmethod
    def _style_str_to_flag(style_str: str) -> sublime.RegionFlags | None: ...
    def diagnostics_highlight_style_flags(self) -> list[sublime.RegionFlags | None]: ...

@dataclass
class SemanticToken:
    region: sublime.Region
    type: str
    modifiers: list[str]

class ClientStates:
    STARTING: int
    READY: int
    STOPPING: int

class DocumentFilterMatcher:
    __slots__: Incomplete
    scheme: Incomplete
    pattern: Incomplete
    language: Incomplete
    def __init__(self, language: str | None = None, scheme: str | None = None, pattern: str | None = None) -> None: ...
    def __call__(self, view: sublime.View) -> bool: ...

class DocumentSelectorMatcher:
    __slots__: Incomplete
    filters: Incomplete
    def __init__(self, document_selector: DocumentSelector) -> None: ...
    def __bool__(self) -> bool: ...
    def matches(self, view: sublime.View) -> bool: ...

def match_file_operation_filters(filters: list[FileOperationFilter], uri: URI) -> bool: ...

_METHOD_TO_CAPABILITY_EXCEPTIONS: dict[str, tuple[str, str | None]]

def method2attr(method: str) -> str: ...
def method_to_capability(method: str) -> tuple[str, str]: ...
def normalize_text_sync(textsync: TextDocumentSyncOptions | TextDocumentSyncKind | None) -> dict[str, Any]: ...

class Capabilities(DottedDict):
    def register(self, registration_id: str, capability_path: str, registration_path: str, options: dict[str, Any]) -> None: ...
    def unregister(self, registration_id: str, capability_path: str, registration_path: str) -> dict[str, Any] | None: ...
    def assign(self, d: ServerCapabilities) -> None: ...
    def should_notify_did_open(self) -> bool: ...
    def text_sync_kind(self) -> TextDocumentSyncKind: ...
    def should_notify_did_change_configuration(self) -> bool: ...
    def should_notify_did_change_workspace_folders(self) -> bool: ...
    def should_notify_will_save(self) -> bool: ...
    def should_notify_did_save(self) -> tuple[bool, bool]: ...
    def should_notify_did_close(self) -> bool: ...

def _translate_path(path: str, source: str, destination: str) -> tuple[str, bool]: ...

class PathMap:
    __slots__: Incomplete
    _local: Incomplete
    _remote: Incomplete
    def __init__(self, local: str, remote: str) -> None: ...
    @classmethod
    def parse(cls, json: Any) -> list[PathMap] | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def map_from_local_to_remote(self, uri: str) -> tuple[str, bool]: ...
    def map_from_remote_to_local(self, uri: str) -> tuple[str, bool]: ...

class DefaultViewStatusHandler(ViewStatusHandler):
    @override
    def on_view_status_changed(self, config_name: str, view: sublime.View, status: str | None) -> None: ...

default_status_view_handler: Incomplete

class ClientConfig:
    name: Incomplete
    selector: Incomplete
    priority_selector: Incomplete
    schemes: list[str]
    command: Incomplete
    tcp_port: Incomplete
    auto_complete_selector: Incomplete
    _enabled: Incomplete
    initialization_options: Incomplete
    settings: Incomplete
    env: Incomplete
    experimental_capabilities: Incomplete
    disabled_capabilities: Incomplete
    file_watcher: Incomplete
    path_maps: Incomplete
    semantic_tokens: Incomplete
    diagnostics_mode: Incomplete
    resolved_markdown_language_map: MarkdownLangMap | None
    _markdown_language_map: Incomplete
    _settings_registration: Incomplete
    _all_settings: Incomplete
    _view_status_handler: Incomplete
    def __init__(self, *, name: str, selector: str, priority_selector: str | None = None, schemes: list[str] | None = None, command: list[str] | None = None, tcp_port: int | None = None, auto_complete_selector: str | None = None, enabled: bool = True, initialization_options: DottedDict | None = None, settings: DottedDict | None = None, env: dict[str, str] | None = None, experimental_capabilities: dict[str, Any] | None = None, disabled_capabilities: DottedDict | None = None, file_watcher: FileWatcherConfig | None = None, semantic_tokens: dict[str, str] | None = None, diagnostics_mode: str = 'all_files', markdown_language_map: MarkdownLangMapJson | None = None, path_maps: list[PathMap] | None = None, settings_registration: SettingsRegistration | None = None, all_settings: dict[str, Any] | None = None) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    @property
    def init_options(self) -> DottedDict: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, enabled: bool) -> None: ...
    @property
    def markdown_language_map(self) -> MarkdownLangMapJson | None: ...
    @markdown_language_map.setter
    def markdown_language_map(self, lang_map: MarkdownLangMapJson | None) -> None: ...
    def _resolve_markdown_language_map(self, lang_map: MarkdownLangMapJson | None) -> MarkdownLangMap | None: ...
    @classmethod
    def from_sublime_settings(cls, name: str, settings_registration: SettingsRegistration) -> ClientConfig: ...
    @classmethod
    def from_dict(cls, name: str, d: dict[str, Any]) -> ClientConfig: ...
    @classmethod
    def from_config(cls, src_config: ClientConfig, override: dict[str, Any]) -> ClientConfig: ...
    def create_transport_config(self) -> TransportConfig: ...
    def set_view_status_handler(self, handler: ViewStatusHandler) -> None: ...
    def set_view_status(self, view: sublime.View, message: str) -> None: ...
    def erase_view_status(self, view: sublime.View) -> None: ...
    def match_view(self, view: sublime.View, scheme: str, window: sublime.Window, workspace_folders: list[WorkspaceFolder]) -> bool: ...
    def map_client_path_to_server_uri(self, path: str) -> str: ...
    def map_server_uri_to_client_path(self, uri: DocumentUri) -> str: ...
    def is_disabled_capability(self, capability_path: str) -> bool: ...
    def filter_out_disabled_capabilities(self, capability_path: str, options: dict[str, Any]) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def _read_selector(config: sublime.Settings | dict[str, Any]) -> str: ...
def _read_priority_selector(config: sublime.Settings | dict[str, Any]) -> str: ...
