import abc
import sublime
from ..protocol import ConfigurationItem as ConfigurationItem, DocumentUri as DocumentUri, ExecuteCommandParams as ExecuteCommandParams, LSPAny
from .core.collections import DottedDict as DottedDict
from .core.constants import MarkdownLangMap as MarkdownLangMap, ST_STORAGE_PATH as ST_STORAGE_PATH
from .core.logging import exception_log as exception_log
from .core.promise import Promise as Promise
from .core.protocol import ClientNotification as ClientNotification, ClientRequest as ClientRequest, ClientResponse as ClientResponse, Notification as Notification, Request as Request, Response as Response, ServerNotification as ServerNotification, ServerResponse as ServerResponse
from .core.sessions import Session as Session, SessionBufferProtocol as SessionBufferProtocol, SessionViewProtocol as SessionViewProtocol
from .core.settings import client_configs as client_configs
from .core.transports import TransportWrapper as TransportWrapper
from .core.types import ClientConfig as ClientConfig, method2attr as method2attr
from .core.url import parse_uri as parse_uri
from .core.views import uri_from_view as uri_from_view
from .core.workspace import WorkspaceFolder as WorkspaceFolder
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Final, TypeVar, final
from weakref import ref as ref

HANDLER_MARKER: str
COMMAND_HANDLER_MARKER: str
URI_HANDLER_MARKER: str
P = TypeVar('P', bound=LSPAny)
R = TypeVar('R', bound=LSPAny)
CommandHandler: Incomplete
CommandHandlerForDecorator: Incomplete
UriHandler: Incomplete
UriHandlerForDecorator: Incomplete
g_plugins: dict[str, type[AbstractPlugin | LspPlugin]]

class PluginStartError(Exception):
    def __init__(self, message: str) -> None: ...

def register_plugin(plugin: type[AbstractPlugin], notify_listener: bool = True) -> None: ...
def register_plugin_impl(plugin: type[AbstractPlugin | LspPlugin], notify_listener: bool = True) -> None: ...
def _register_plugin_impl(plugin: type[AbstractPlugin | LspPlugin], notify_listener: bool) -> None: ...
def unregister_plugin(plugin: type[AbstractPlugin]) -> None: ...
def unregister_plugin_impl(plugin: type[AbstractPlugin | LspPlugin]) -> None: ...
def get_plugin(name: str) -> type[AbstractPlugin | LspPlugin] | None: ...

class APIHandler:
    handler_attr_map: dict[str, str]
    _command_handler_map: dict[str, str]
    _uri_handler_map: dict[str, str]
    def __init__(self) -> None: ...
    def get_command_handler(self, command_name: str) -> CommandHandler[P, R] | None: ...
    def get_uri_handler(self, scheme: str) -> UriHandler | None: ...

def notification_handler(method: str) -> Callable[[Callable[[Any, P], None]], Callable[[Any, P], None]]: ...
def request_handler(method: str) -> Callable[[Callable[[Any, P], Promise[R]]], Callable[[Any, P, int], Promise[Response[R]]]]: ...
def command_handler(command_name: str) -> Callable[[CommandHandlerForDecorator], CommandHandlerForDecorator]: ...
def uri_handler(scheme: str) -> Callable[[UriHandlerForDecorator], UriHandlerForDecorator]: ...

@dataclass
class IsApplicableContext:
    configuration: ClientConfig
    view: sublime.View
    workspace_folders: list[WorkspaceFolder]

@dataclass
class OnPreStartContext:
    configuration: ClientConfig
    variables: dict[str, str]
    view: sublime.View
    working_directory: str | None
    workspace_folders: list[WorkspaceFolder]

class LspPlugin(APIHandler):
    name: Final[str]
    plugin_storage_path: Final[Path]
    @classmethod
    @final
    def register(cls) -> None: ...
    @classmethod
    @final
    def unregister(cls) -> None: ...
    @classmethod
    def is_applicable_async(cls, context: IsApplicableContext) -> bool: ...
    @classmethod
    def on_pre_start_async(cls, context: OnPreStartContext) -> None: ...
    weaksession: ref[Session]
    def __init__(self, weaksession: ref[Session]) -> None: ...
    def __init_subclass__(cls, **kwargs: Any) -> None: ...
    def on_transport_ready_async(self, transport: TransportWrapper) -> None: ...
    def on_initialize_async(self) -> None: ...
    def on_pre_send_request_async(self, request: ClientRequest, view: sublime.View | None) -> None: ...
    def on_pre_send_response_async(self, response: ClientResponse) -> None: ...
    def on_pre_send_notification_async(self, notification: ClientNotification) -> None: ...
    def on_server_response_async(self, response: ServerResponse) -> None: ...
    def on_server_notification_async(self, notification: ServerNotification) -> None: ...
    def on_text_changed_async(self, session_buffer: SessionBufferProtocol) -> None: ...
    def on_selection_modified_async(self, session_view: SessionViewProtocol) -> None: ...
    def on_session_end_async(self, exit_code: int | None, exception: Exception | None) -> None: ...

class AbstractPlugin(APIHandler, ABC, metaclass=abc.ABCMeta):
    @classmethod
    @abstractmethod
    def name(cls) -> str: ...
    @classmethod
    def configuration(cls) -> tuple[sublime.Settings, str]: ...
    @classmethod
    def is_applicable(cls, view: sublime.View, config: ClientConfig) -> bool: ...
    @classmethod
    def additional_variables(cls) -> dict[str, str] | None: ...
    @classmethod
    def storage_path(cls) -> str: ...
    @classmethod
    def needs_update_or_installation(cls) -> bool: ...
    @classmethod
    def install_or_update(cls) -> None: ...
    @classmethod
    def can_start(cls, window: sublime.Window, initiating_view: sublime.View, workspace_folders: list[WorkspaceFolder], configuration: ClientConfig) -> str | None: ...
    @classmethod
    def on_pre_start(cls, window: sublime.Window, initiating_view: sublime.View, workspace_folders: list[WorkspaceFolder], configuration: ClientConfig) -> str | None: ...
    @classmethod
    def on_post_start(cls, window: sublime.Window, initiating_view: sublime.View, workspace_folders: list[WorkspaceFolder], configuration: ClientConfig) -> None: ...
    @classmethod
    def markdown_language_id_to_st_syntax_map(cls) -> MarkdownLangMap | None: ...
    weaksession: Incomplete
    def __init__(self, weaksession: ref[Session]) -> None: ...
    def on_settings_changed(self, settings: DottedDict) -> None: ...
    def on_workspace_configuration(self, params: ConfigurationItem, configuration: Any) -> Any: ...
    def on_pre_server_command(self, command: ExecuteCommandParams, done_callback: Callable[[], None]) -> bool: ...
    def on_pre_send_request_async(self, request_id: int, request: Request[Any, Any]) -> None: ...
    def on_pre_send_notification_async(self, notification: Notification[Any]) -> None: ...
    def on_server_response_async(self, method: str, response: Response[Any]) -> None: ...
    def on_server_notification_async(self, notification: Notification[Any]) -> None: ...
    def on_open_uri_async(self, uri: DocumentUri, callback: Callable[[str | None, str, str], None]) -> bool: ...
    def on_session_buffer_changed_async(self, session_buffer: SessionBufferProtocol) -> None: ...
    def on_selection_modified_async(self, session_view: SessionViewProtocol) -> None: ...
    def on_session_end_async(self, exit_code: int | None, exception: Exception | None) -> None: ...
