import sublime
import sublime_plugin
from .core.registry import LspTextCommand as LspTextCommand
from .core.settings import userprefs as userprefs
from abc import ABCMeta, abstractmethod
from typing import Any, Callable

class SaveTask(metaclass=ABCMeta):
    @classmethod
    @abstractmethod
    def is_applicable(cls, view: sublime.View) -> bool: ...
    def __init__(self, task_runner: LspTextCommand, on_done: Callable[[], None]) -> None: ...
    def run_async(self) -> None: ...
    def cancel(self) -> None: ...

class SaveTasksRunner:
    def __init__(self, text_command: LspTextCommand, tasks: list[type[SaveTask]], on_complete: Callable[[], None]) -> None: ...
    def run(self) -> None: ...
    def cancel(self) -> None: ...

class LspSaveCommand(LspTextCommand):
    @classmethod
    def register_task(cls, task: type[SaveTask]) -> None: ...
    def __init__(self, view: sublime.View) -> None: ...
    def run(self, edit: sublime.Edit, **kwargs: dict[str, Any]) -> None: ...

class LspSaveAllCommand(sublime_plugin.WindowCommand):
    def run(self, only_files: bool = False) -> None: ...
