import sublime
from ..protocol import CodeAction as CodeAction, CodeActionContext as CodeActionContext, CodeActionKind as CodeActionKind, CodeActionParams as CodeActionParams, CodeActionTriggerKind, CodeLens as CodeLens, ColorInformation as ColorInformation, Command as Command, Diagnostic as Diagnostic, DiagnosticSeverity as DiagnosticSeverity, DiagnosticTag as DiagnosticTag, DocumentDiagnosticParams as DocumentDiagnosticParams, DocumentDiagnosticReport as DocumentDiagnosticReport, DocumentLink as DocumentLink, DocumentOnTypeFormattingOptions as DocumentOnTypeFormattingOptions, DocumentOnTypeFormattingParams as DocumentOnTypeFormattingParams, DocumentUri as DocumentUri, FullDocumentDiagnosticReport as FullDocumentDiagnosticReport, InlayHint as InlayHint, InlayHintParams as InlayHintParams, RelatedFullDocumentDiagnosticReport as RelatedFullDocumentDiagnosticReport, SemanticTokens as SemanticTokens, SemanticTokensDelta as SemanticTokensDelta, TextDocumentSyncKind, TextEdit as TextEdit, UnchangedDocumentDiagnosticReport as UnchangedDocumentDiagnosticReport
from .api import LspPlugin as LspPlugin
from .code_lens import CodeLensCache as CodeLensCache, LspToggleCodeLensesCommand as LspToggleCodeLensesCommand
from .core.constants import AUTO_CLOSE_BRACKETS as AUTO_CLOSE_BRACKETS, CODE_LENS_ANNOTATION_SCOPE as CODE_LENS_ANNOTATION_SCOPE, ChangeEventAction as ChangeEventAction, DIAGNOSTIC_TAG_SCOPES as DIAGNOSTIC_TAG_SCOPES, DOCUMENT_LINK_FLAGS as DOCUMENT_LINK_FLAGS, RegionKey as RegionKey, RequestFlags as RequestFlags, SEMANTIC_TOKENS_MAP as SEMANTIC_TOKENS_MAP, SEMANTIC_TOKEN_FLAGS as SEMANTIC_TOKEN_FLAGS, SUPPORTED_DIAGNOSTIC_TAGS as SUPPORTED_DIAGNOSTIC_TAGS
from .core.edit import apply_text_edits as apply_text_edits
from .core.promise import Promise as Promise
from .core.protocol import Error as Error, Request as Request, ResolvedCodeLens as ResolvedCodeLens, ResponseError as ResponseError
from .core.sessions import Session as Session, SessionViewProtocol as SessionViewProtocol, is_diagnostic_server_cancellation_data as is_diagnostic_server_cancellation_data
from .core.settings import userprefs as userprefs
from .core.types import Capabilities as Capabilities, DebouncerNonThreadSafe as DebouncerNonThreadSafe, FEATURES_TIMEOUT as FEATURES_TIMEOUT, SemanticToken as SemanticToken, debounced as debounced
from .core.url import normalize_uri as normalize_uri
from .core.views import DiagnosticSeverityData as DiagnosticSeverityData, MissingUriError as MissingUriError, diagnostic_severity as diagnostic_severity, did_change as did_change, did_close as did_close, did_open as did_open, did_save as did_save, document_color_params as document_color_params, entire_content_range as entire_content_range, first_selection_region as first_selection_region, formatting_options as formatting_options, lsp_color_to_phantom as lsp_color_to_phantom, range_to_region as range_to_region, region_to_range as region_to_range, text_document_identifier as text_document_identifier, text_document_position_params as text_document_position_params, will_save as will_save
from .diagnostics import DOCUMENT_DIAGNOSTICS_RETRIGGER_DELAY as DOCUMENT_DIAGNOSTICS_RETRIGGER_DELAY, DiagnosticsIdentifier as DiagnosticsIdentifier
from .inlay_hint import inlay_hint_to_phantom as inlay_hint_to_phantom
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any, Callable
from typing_extensions import Concatenate, ParamSpec, TypeGuard
from weakref import WeakSet

P = ParamSpec('P')
HUGE_FILE_SIZE: int

def is_full_document_diagnostic_report(diagnostic_report: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport) -> TypeGuard[FullDocumentDiagnosticReport]: ...
def is_related_full_document_diagnostic_report(diagnostic_report: DocumentDiagnosticReport) -> TypeGuard[RelatedFullDocumentDiagnosticReport]: ...

class PendingChanges:
    __slots__: Incomplete
    version: Incomplete
    changes: Incomplete
    def __init__(self, version: int, changes: list[sublime.TextChange]) -> None: ...
    def update(self, version: int, changes: list[sublime.TextChange]) -> None: ...

@dataclass
class PendingDocumentDiagnosticRequest:
    version: int
    request_id: int

class SemanticTokensData:
    __slots__: Incomplete
    data: list[int]
    result_id: str | None
    active_region_keys: set[int]
    tokens: list[SemanticToken]
    view_change_count: int
    pending_response: int | None
    def __init__(self) -> None: ...

class SessionBuffer:
    opened: bool
    capabilities: Incomplete
    _session: Incomplete
    _session_views: WeakSet[SessionViewProtocol]
    _last_known_uri: Incomplete
    _id: Incomplete
    _pending_changes: PendingChanges | None
    pending_refreshes: RequestFlags
    _diagnostics: list[tuple[Diagnostic, sublime.Region]]
    diagnostics_data_per_severity: dict[tuple[DiagnosticSeverity, bool], DiagnosticSeverityData]
    _diagnostics_versions: dict[DiagnosticsIdentifier, int]
    diagnostics_flags: int
    _diagnostics_are_visible: bool
    supported_diagnostic_tags: set[DiagnosticTag]
    _document_diagnostic_pending_requests: dict[DiagnosticsIdentifier, PendingDocumentDiagnosticRequest | None]
    _last_synced_version: int
    _last_text_change_time: float
    _diagnostics_debouncer_async: Incomplete
    _color_phantoms: Incomplete
    _document_links: list[DocumentLink]
    semantic_tokens: Incomplete
    _semantic_region_keys: dict[str, int]
    _semantic_highlighting_supported_by_color_scheme: bool
    _supported_custom_tokens: set[str]
    _last_semantic_region_key: int
    _inlay_hints_phantom_set: Incomplete
    _is_saving: bool
    _has_changed_during_save: bool
    _code_lenses: Incomplete
    code_lens_annotation_color: str
    _dynamically_registered_commands: dict[str, list[str]]
    _supported_commands: set[str]
    _on_type_formatting_triggers: tuple[str, ...]
    def __init__(self, session_view: SessionViewProtocol, buffer_id: int, uri: DocumentUri) -> None: ...
    @property
    def session(self) -> Session: ...
    @property
    def session_views(self) -> WeakSet[SessionViewProtocol]: ...
    @property
    def diagnostics(self) -> list[tuple[Diagnostic, sublime.Region]]: ...
    @property
    def last_synced_version(self) -> int: ...
    def on_session_view_initialized(self, view: sublime.View) -> None: ...
    def _check_did_open(self, view: sublime.View) -> None: ...
    def _check_did_close(self, view: sublime.View) -> None: ...
    def get_uri(self) -> DocumentUri | None: ...
    def get_language_id(self) -> str | None: ...
    def get_view_in_group(self, group: int = -1) -> sublime.View: ...
    @property
    def language_id(self) -> str: ...
    def add_session_view(self, sv: SessionViewProtocol) -> None: ...
    def remove_session_view(self, sv: SessionViewProtocol) -> None: ...
    def _on_before_destroy(self, view: sublime.View) -> None: ...
    def register_capability_async(self, registration_id: str, capability_path: str, registration_path: str, options: dict[str, Any], suppress_requests: bool) -> None: ...
    def unregister_capability_async(self, registration_id: str, capability_path: str, registration_path: str) -> None: ...
    def get_capability(self, capability_path: str) -> Any | None: ...
    def has_capability(self, capability_path: str) -> bool: ...
    def text_sync_kind(self) -> TextDocumentSyncKind: ...
    def should_notify_did_open(self) -> bool: ...
    def should_notify_will_save(self) -> bool: ...
    def should_notify_did_save(self) -> tuple[bool, bool]: ...
    def should_notify_did_close(self) -> bool: ...
    def on_text_changed_async(self, view: sublime.View, change_count: int, changes: list[sublime.TextChange], action: ChangeEventAction) -> None: ...
    def _cancel_pending_requests_async(self) -> None: ...
    def on_revert_async(self, view: sublime.View) -> None: ...
    on_reload_async = on_revert_async
    def purge_changes_async(self, view: sublime.View, suppress_requests: bool = False) -> None: ...
    def _on_after_change_async(self, view: sublime.View, version: int, suppress_requests: bool = False) -> None: ...
    def on_pre_save_async(self, view: sublime.View) -> None: ...
    def on_post_save_async(self, view: sublime.View, new_uri: DocumentUri) -> None: ...
    def on_userprefs_changed_async(self) -> None: ...
    def on_color_scheme_changed(self, view: sublime.View) -> None: ...
    def some_view(self) -> sublime.View | None: ...
    def set_pending_refresh(self, flags: RequestFlags) -> None: ...
    def _reset_pending_refresh(self, flags: RequestFlags) -> None: ...
    def _if_view_unchanged(self, f: Callable[Concatenate[sublime.View, P], None], version: int) -> Callable[P, None]: ...
    def _update_color_scheme_rules(self, view: sublime.View) -> None: ...
    def _update_supported_commands(self) -> None: ...
    def _get_request_flags(self, view: sublime.View) -> RequestFlags: ...
    def _do_color_boxes_async(self, view: sublime.View, version: int) -> None: ...
    def _on_color_boxes_async(self, view: sublime.View, response: list[ColorInformation] | None) -> None: ...
    def clear_color_boxes_async(self) -> None: ...
    def _do_document_link_async(self, view: sublime.View, version: int) -> None: ...
    def _on_document_link_async(self, view: sublime.View, response: list[DocumentLink] | None) -> None: ...
    def _redraw_document_links_async(self) -> None: ...
    def get_document_link_at_point(self, view: sublime.View, point: int) -> DocumentLink | None: ...
    def update_document_link(self, new_link: DocumentLink) -> None: ...
    def do_document_diagnostic_async(self, view: sublime.View, version: int, *, forced_update: bool = False) -> None: ...
    def _do_document_diagnostic_async(self, view: sublime.View, identifier: DiagnosticsIdentifier, version: int, *, forced_update: bool = False) -> None: ...
    def _on_document_diagnostic_async(self, identifier: DiagnosticsIdentifier, version: int, response: DocumentDiagnosticReport) -> None: ...
    def _on_document_diagnostic_error_async(self, view: sublime.View, identifier: DiagnosticsIdentifier, version: int, error: ResponseError) -> None: ...
    def on_diagnostics_async(self, raw_diagnostics: list[Diagnostic], version: int | None, visible_session_views: set[SessionViewProtocol]) -> None: ...
    def has_latest_diagnostics(self) -> bool: ...
    def _update_on_type_formatting_triggers(self) -> None: ...
    def _get_on_type_formatting_params_async(self, view: sublime.View, action: ChangeEventAction, text: str) -> DocumentOnTypeFormattingParams | None: ...
    def _create_on_type_formatting_params_async(self, view: sublime.View, trigger: str) -> DocumentOnTypeFormattingParams | None: ...
    def _on_type_formatting_result_async(self, view: sublime.View, version: int, result: list[TextEdit] | Error | None) -> None: ...
    def do_semantic_tokens_async(self, view: sublime.View, only_viewport: bool = False) -> None: ...
    def _on_semantic_tokens_async(self, response: SemanticTokens | None) -> None: ...
    def _on_semantic_tokens_viewport_async(self, view: sublime.View, response: SemanticTokens | None) -> None: ...
    def _on_semantic_tokens_delta_async(self, response: SemanticTokens | SemanticTokensDelta | None) -> None: ...
    def _on_semantic_tokens_error_async(self, _: ResponseError) -> None: ...
    def _draw_semantic_tokens_async(self) -> None: ...
    def _get_semantic_region_key_for_scope(self, scope: str) -> int: ...
    def _clear_semantic_token_regions(self, view: sublime.View) -> None: ...
    def get_semantic_tokens(self) -> list[SemanticToken]: ...
    def clear_semantic_tokens_async(self) -> None: ...
    def do_inlay_hints_async(self, view: sublime.View) -> None: ...
    def _on_inlay_hints_async(self, response: list[InlayHint] | None) -> None: ...
    def present_inlay_hints(self, phantoms: list[sublime.Phantom]) -> None: ...
    def remove_inlay_hint_phantom(self, phantom_uuid: str) -> None: ...
    def remove_all_inlay_hints(self) -> None: ...
    def request_code_actions_async(self, view: sublime.View, region: sublime.Region, diagnostics: list[Diagnostic], kinds: list[str | CodeActionKind] | None = None, trigger_kind: CodeActionTriggerKind = ...) -> Promise[list[Command | CodeAction] | Error | None]: ...
    def do_code_lenses_async(self, view: sublime.View) -> None: ...
    def _on_code_lenses_async(self, view: sublime.View, response: list[CodeLens] | None) -> None: ...
    def resolve_visible_code_lenses_async(self, view: sublime.View) -> None: ...
    def _filter_supported_code_lenses(self) -> list[ResolvedCodeLens]: ...
    def _on_visible_code_lenses_resolved_async(self) -> None: ...
    def __str__(self) -> str: ...
