import sublime
from .core.constants import DOCUMENT_LINK_FLAGS as DOCUMENT_LINK_FLAGS, RegionKey as RegionKey, SEMANTIC_TOKEN_FLAGS as SEMANTIC_TOKEN_FLAGS
from .core.protocol import ColorInformation as ColorInformation, Diagnostic as Diagnostic, DocumentDiagnosticParams as DocumentDiagnosticParams, DocumentDiagnosticReport as DocumentDiagnosticReport, DocumentDiagnosticReportKind as DocumentDiagnosticReportKind, DocumentLink as DocumentLink, DocumentUri as DocumentUri, FullDocumentDiagnosticReport as FullDocumentDiagnosticReport, InlayHint as InlayHint, InlayHintParams as InlayHintParams, LSPErrorCodes as LSPErrorCodes, Request as Request, ResponseError as ResponseError, SemanticTokensDeltaParams as SemanticTokensDeltaParams, SemanticTokensParams as SemanticTokensParams, SemanticTokensRangeParams as SemanticTokensRangeParams, TextDocumentSaveReason as TextDocumentSaveReason, TextDocumentSyncKind as TextDocumentSyncKind
from .core.sessions import Session as Session, SessionViewProtocol as SessionViewProtocol, is_diagnostic_server_cancellation_data as is_diagnostic_server_cancellation_data
from .core.settings import userprefs as userprefs
from .core.types import Capabilities as Capabilities, DebouncerNonThreadSafe as DebouncerNonThreadSafe, FEATURES_TIMEOUT as FEATURES_TIMEOUT, WORKSPACE_DIAGNOSTICS_TIMEOUT as WORKSPACE_DIAGNOSTICS_TIMEOUT, debounced as debounced
from .core.views import DiagnosticSeverityData as DiagnosticSeverityData, MissingUriError as MissingUriError, diagnostic_severity as diagnostic_severity, did_change as did_change, did_close as did_close, did_open as did_open, did_save as did_save, document_color_params as document_color_params, entire_content_range as entire_content_range, lsp_color_to_phantom as lsp_color_to_phantom, range_to_region as range_to_region, region_to_range as region_to_range, text_document_identifier as text_document_identifier, will_save as will_save
from .inlay_hint import inlay_hint_to_phantom as inlay_hint_to_phantom
from .semantic_highlighting import SemanticToken as SemanticToken
from _typeshed import Incomplete
from typing import Any, Iterable, Protocol
from typing_extensions import TypeGuard
from weakref import WeakSet

HUGE_FILE_SIZE: int

class CallableWithOptionalArguments(Protocol):
    def __call__(self, *args: Any) -> None: ...

def is_full_document_diagnostic_report(response: DocumentDiagnosticReport) -> TypeGuard[FullDocumentDiagnosticReport]: ...

class PendingChanges:
    version: Incomplete
    changes: Incomplete
    def __init__(self, version: int, changes: Iterable[sublime.TextChange]) -> None: ...
    def update(self, version: int, changes: Iterable[sublime.TextChange]) -> None: ...

class PendingDocumentDiagnosticRequest:
    version: Incomplete
    request_id: Incomplete
    def __init__(self, version: int, request_id: int) -> None: ...

class SemanticTokensData:
    data: Incomplete
    result_id: Incomplete
    active_region_keys: Incomplete
    tokens: Incomplete
    view_change_count: int
    needs_refresh: bool
    pending_response: Incomplete
    def __init__(self) -> None: ...

class SessionBuffer:
    opened: bool
    capabilities: Incomplete
    diagnostics: Incomplete
    diagnostics_data_per_severity: Incomplete
    diagnostics_flags: int
    document_diagnostic_needs_refresh: bool
    semantic_tokens: Incomplete
    inlay_hints_needs_refresh: bool
    def __init__(self, session_view: SessionViewProtocol, buffer_id: int, uri: DocumentUri) -> None: ...
    @property
    def session(self) -> Session: ...
    @property
    def session_views(self) -> WeakSet[SessionViewProtocol]: ...
    @property
    def version(self) -> int | None: ...
    def get_uri(self) -> DocumentUri | None: ...
    def get_language_id(self) -> str | None: ...
    def get_view_in_group(self, group: int) -> sublime.View: ...
    @property
    def language_id(self) -> str: ...
    def add_session_view(self, sv: SessionViewProtocol) -> None: ...
    def remove_session_view(self, sv: SessionViewProtocol) -> None: ...
    def register_capability_async(self, registration_id: str, capability_path: str, registration_path: str, options: dict[str, Any]) -> None: ...
    def unregister_capability_async(self, registration_id: str, capability_path: str, registration_path: str) -> None: ...
    def get_capability(self, capability_path: str) -> Any | None: ...
    def has_capability(self, capability_path: str) -> bool: ...
    def text_sync_kind(self) -> TextDocumentSyncKind: ...
    def should_notify_did_open(self) -> bool: ...
    def should_notify_will_save(self) -> bool: ...
    def should_notify_did_save(self) -> tuple[bool, bool]: ...
    def should_notify_did_close(self) -> bool: ...
    def on_text_changed_async(self, view: sublime.View, change_count: int, changes: Iterable[sublime.TextChange]) -> None: ...
    def on_revert_async(self, view: sublime.View) -> None: ...
    on_reload_async = on_revert_async
    def purge_changes_async(self, view: sublime.View, suppress_requests: bool = False) -> None: ...
    def on_pre_save_async(self, view: sublime.View) -> None: ...
    def on_post_save_async(self, view: sublime.View, new_uri: DocumentUri) -> None: ...
    def on_userprefs_changed_async(self) -> None: ...
    def some_view(self) -> sublime.View | None: ...
    def get_document_link_at_point(self, view: sublime.View, point: int) -> DocumentLink | None: ...
    def update_document_link(self, new_link: DocumentLink) -> None: ...
    def do_document_diagnostic_async(self, view: sublime.View, version: int | None = None, forced_update: bool = False) -> None: ...
    def set_document_diagnostic_pending_refresh(self, needs_refresh: bool = True) -> None: ...
    def on_diagnostics_async(self, raw_diagnostics: list[Diagnostic], version: int | None, visible_session_views: set[SessionViewProtocol]) -> None: ...
    def has_latest_diagnostics(self) -> bool: ...
    def do_semantic_tokens_async(self, view: sublime.View, only_viewport: bool = False) -> None: ...
    def set_semantic_tokens_pending_refresh(self, needs_refresh: bool = True) -> None: ...
    def get_semantic_tokens(self) -> list[SemanticToken]: ...
    def do_inlay_hints_async(self, view: sublime.View) -> None: ...
    def present_inlay_hints(self, phantoms: list[sublime.Phantom]) -> None: ...
    def set_inlay_hints_pending_refresh(self, needs_refresh: bool = True) -> None: ...
    def remove_inlay_hint_phantom(self, phantom_uuid: str) -> None: ...
    def remove_all_inlay_hints(self) -> None: ...
