from _typeshed import Incomplete
from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import Any, Callable

StringCallback = Callable[[str], None]
SemanticVersion = tuple[int, int, int]
is_windows: Incomplete

def platform_program_file_extension() -> str: ...
def run_command_sync(args: Sequence[str | PathLike[str]], cwd: str | PathLike[str] | None = None, env: dict[str, str] | None = None, extra_env: dict[str, str] | None = None, extra_paths: list[str] | None = None, *, shell: bool = ...) -> tuple[str, str | None]: ...
def run_command_async(args: Sequence[str | PathLike[str]], on_success: StringCallback, on_error: StringCallback, **kwargs: Any) -> None: ...
def run_command_ex(*cmd: str | PathLike[str], cwd: str | PathLike[str] | None = None) -> str: ...
def decode_bytes(data: bytes) -> str: ...
def rmtree_ex(path: str | Path, *, ignore_errors: bool = False) -> None: ...
def version_to_string(version: SemanticVersion) -> str: ...
