import os
import subprocess
from .helpers import SemanticVersion
from .third_party.semantic_version import NpmSpec, Version
from _typeshed import Incomplete
from pathlib import Path
from typing import Any
from typing_extensions import override

__all__ = ['NodeRuntime']

class NodeRuntime:
    _node_runtime_resolved: bool
    _node_runtime: NodeRuntime | None
    @classmethod
    def get(cls, package_name: str, storage_path: str, required_node_version: str | SemanticVersion) -> NodeRuntime | None: ...
    @classmethod
    def _resolve_node_runtime(cls, package_name: str, storage_path: Path, required_node_version: NpmSpec) -> NodeRuntime: ...
    _node: Path | None
    _npm: Path | None
    _version: Version | None
    _additional_paths: list[str]
    def __init__(self) -> None: ...
    @override
    def __repr__(self) -> str: ...
    def install_node(self) -> None: ...
    def node_bin(self) -> str | None: ...
    def npm_bin(self) -> str | None: ...
    def node_env(self) -> dict[str, str]: ...
    def check_binary_present(self) -> None: ...
    def check_satisfies_version(self, required_node_version: NpmSpec) -> None: ...
    def resolve_version(self) -> Version: ...
    def run_node(self, args: list[str], stdin: int = ..., stdout: int = ..., stderr: int = ..., env: dict[str, Any] | None = None) -> subprocess.Popen[bytes] | None: ...
    def run_install(self, cwd: str | os.PathLike[str]) -> None: ...
    def npm_command(self) -> list[Path]: ...

class NodeRuntimePATH(NodeRuntime):
    _node: Incomplete
    _npm: Incomplete
    def __init__(self) -> None: ...

class NodeRuntimeLocal(NodeRuntime):
    _base_dir: Incomplete
    _node_version: Incomplete
    _node_dir: Incomplete
    _node_dist_url: Incomplete
    _install_in_progress_marker_file: Incomplete
    def __init__(self, base_dir: Path, node_version: str = ..., node_dist_url: str = ...) -> None: ...
    @override
    def npm_command(self) -> list[Path]: ...
    @override
    def install_node(self) -> None: ...
    _node: Incomplete
    _node_lib: Incomplete
    _npm: Incomplete
    _additional_paths: Incomplete
    def _resolve_paths(self) -> None: ...
    def _resolve_binary(self) -> Path | None: ...
    def _resolve_lib(self) -> Path: ...

class NodeInstaller:
    _base_dir: Incomplete
    _node_version: Incomplete
    _node_dist_url: Incomplete
    _cache_dir: Incomplete
    def __init__(self, base_dir: Path, node_version: str, node_dist_url: str) -> None: ...
    def run(self) -> None: ...
    def _node_archive(self) -> tuple[str, str]: ...
    def _install_node(self, archive_path: Path) -> None: ...

class ElectronRuntimeLocal(NodeRuntime):
    _base_dir: Incomplete
    _yarn: Incomplete
    _install_in_progress_marker_file: Incomplete
    def __init__(self, base_dir: Path) -> None: ...
    @override
    def node_env(self) -> dict[str, str]: ...
    @override
    def install_node(self) -> None: ...
    @override
    def run_install(self, cwd: str | os.PathLike[str]) -> None: ...
    _node: Incomplete
    _npm: Incomplete
    def _resolve_paths(self) -> None: ...
    def _resolve_binary(self) -> Path | None: ...
    def _run_yarn(self, args: list[str], cwd: str | os.PathLike[str]) -> None: ...

class ElectronInstaller:
    _base_dir: Incomplete
    _cache_dir: Incomplete
    def __init__(self, base_dir: Path) -> None: ...
    def run(self) -> None: ...
    def _node_archive(self) -> tuple[str, str]: ...
    def _install(self, archive_path: Path) -> None: ...
