from _typeshed import Incomplete
from pathlib import Path

__all__ = ['PipVenvManager']

class PipVenvManager:
    _venv_path: Incomplete
    _requirements_resource_path: Incomplete
    _python_binary: Incomplete
    def __init__(self, venv_path: Path, requirements_path: str, python_binary: str) -> None: ...
    @property
    def venv_path(self) -> Path: ...
    @property
    def venv_bin_path(self) -> Path: ...
    @property
    def _venv_pip_binary(self) -> Path: ...
    @property
    def _python_version_path(self) -> Path: ...
    def needs_install_or_update(self) -> bool: ...
    def install(self) -> None: ...
